### ISSUE TITLE
Lets begin!

### ISSUE THREAD

**Issue by raavimunaf** [kylel/jsc#1]
All we need is to start working on it

**Comment by kylel** [comment]
I'm keen. Started looking into it and then got bogged down by the details. do you have any ideas on where to start?

**Comment by raavimunaf** [comment]
Google for JSCPP there's a project but that's for c++, Do have a look at it!

**Comment by kylel** [comment]
okay so its been a while. I've done some research and I'm ready to start. expect some work here soon
